language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
# command to install dependencies
before_install:
    - "pip install ."
    - "pip install -r requirements.txt"
    - "pip install coveralls"
# command to run tests
script: 
    - python setup.py test
after_success:
    - coveralls