language: python
python:
    - "2.7"
    - "3.6"
    - "pypy"
# command to install dependencies
before_install:
    - "pip install ."
    - "pip install -r requirements.txt"
    - "pip install coveralls"
# command to run tests
script: 
    - python setup.py test
# command to test coverage, but only on 3.6
after_success:
    - if [[ $ENV == python=3.6* ]]; then
          coveralls;
      fi